version: '3.8'

services:
  uwscheduleexporter:
    build: .
    ports:
      - "8111:8111"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8111/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
